Made a shitty styled site
Tixcu/itc-frontend pull request #2
Opened 2018-03-16 16:22 UTC by Tixcu

Made a shitty styled site

2018-03-18 08:21 UTC, mlshv requested changes

2018-03-18 08:21 UTC, mlshv commented on homework 1/css/style.css
> +    color: white;
не понял

2018-03-18 08:21 UTC, mlshv commented on homework 1/css/style.css
> +.mainBase {
почему классы в camelCase?

2018-03-18 08:21 UTC, mlshv commented on homework 1/css/style.css
> +    background-repeat: no-repeat;
отступ

2018-03-18 08:21 UTC, mlshv commented on homework 0/index.html
> +<!DOCTYPE html>
не понял откуда тут нулевая домашка взялась

2018-03-18 08:21 UTC, mlshv commented on homework 1/index.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
о, вау, джиквери

2018-03-18 08:21 UTC, mlshv commented on homework 1/index.html
> +                dataBase = dataBase['data']['children']
лучше data.data.children

2018-03-18 08:21 UTC, mlshv commented on homework 1/index.html
> +                    let img = "<img src =" + (post['data']['thumbnail']=='default'? 'img/blank.jpg': post['data']['thumbnail']) + '>'
зачем var и let? читай частые ошибки

2018-03-18 11:08 UTC, Tixcu commented on homework 0/index.html
> +<!DOCTYPE html>
Сам не понял =/

2018-04-22 19:02 UTC, mlshv commented
Ладно, главное работает. Бест практисес JS'a можно и на деливери познать

2018-04-22 19:02 UTC, merged